apiVersion: v1
kind: Service
metadata:
  name: hungover-service
  namespace: hungover
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: hungover
  type: NodePort
